### ISSUE TITLE
Please add README.md

### ISSUE THREAD

**Issue by luzpaz** [HakanSeven12/Modern-UI#1]
I can add it if you wish?

**Comment by HakanSeven12** [comment]
Yes. That would be great :)

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/78677007-33b2f000-78b5-11ea-9a61-4bb6a4522e8a.png)
![image](https://user-images.githubusercontent.com/4140247/78677039-40374880-78b5-11ea-88f0-2cc708317f20.png)
![image](https://user-images.githubusercontent.com/4140247/78677068-49281a00-78b5-11ea-935e-b791ed27aa4d.png)
![image](https://user-images.githubusercontent.com/4140247/78677088-4fb69180-78b5-11ea-87cf-8715ef537280.png)
![image](https://user-images.githubusercontent.com/4140247/78677126-5513dc00-78b5-11ea-971c-bdf654261913.png)

**Comment by luzpaz** [comment]
@HakanSeven12 do you mind re-uploading the animated gifs and relevant images in to this github issue? (so i can reference them in the README.md) For some reason transferring them from the FC forum to here breaks them.

**Comment by HakanSeven12** [comment]
![ModernMenu](https://user-images.githubusercontent.com/3831435/78682763-17d03e00-78f7-11ea-9454-e7cc2cf1f8b3.gif)
![ModernDock](https://user-images.githubusercontent.com/3831435/78682773-1a329800-78f7-11ea-9570-2c789cf7fbe0.gif)
![Standart](https://user-images.githubusercontent.com/3831435/78682759-143cb700-78f7-11ea-9363-95e1fc99cc95.png)
![BigIcons](https://user-images.githubusercontent.com/3831435/78682762-156de400-78f7-11ea-8590-0af6633e86ca.png)

**Comment by HakanSeven12** [comment]
what about this one :)

**Comment by luzpaz** [comment]
we still need to add some info to it. 
- [x] Link to the forum thread (there are several so just choose the one most appropriate). 
- [ ] Installation instructions for windows
- [x] Captions for the screenshots

**Comment by HakanSeven12** [comment]
Can you add it to addon manager? It's the easiest way to install.
I created a video on youtube I think to remove pictures and gifs and add only video.
