### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by climoge** [HakanSeven12/Modern-UI#12]
Shortcuts don't work on FreeCAD 0.19 (Windows 10) with addition of Modern-UI. Uninstalling Modern-UI solves the problem.

**Comment by HakanSeven12** [comment]
Yes some of the shortcuts not working. I don't have a solution yet. Sorry.

**Comment by HakanSeven12** [comment]
Fixed

**Comment by climoge** [comment]
Thanks ! Good work !

**Comment by HakanSeven12** [comment]
You are welcome 😉
