### ISSUE TITLE
Pinning Combo view doesn't work

### ISSUE THREAD

**Issue by viktak** [HakanSeven12/Modern-UI#15]
Hi and thanks for this awesome looking add-on!

I just started using this new UI that, in general, looks much better than the original. However, I noticed, that I cannot pin the Combo view to be always on. When I pin it, it stays there until I go into any other view, like a sketch, and it immediately reverts to not pinned and it disappears.

If there is a setting somewhere to control this, then I haven't found it yet. :)

**Comment by HakanSeven12** [comment]
Thats a known issue :) Only think that I can say is you can turn off collapsable dock from modern settings.

**Comment by viktak** [comment]
Cool, This is good enough for my purposes. Thanks for the tip.

Shall I close this issue?

**Comment by HakanSeven12** [comment]
I can do it for you 😁
