### ISSUE TITLE
make auto-collapse actually toggleable, independently on each menu.

### ISSUE THREAD

**Issue by larsbirger** [HakanSeven12/Modern-UI#28]
Currently, I can click the "pin menu" button on the combo view, but once it goes between Model and Tasks in the combo view, the "pin menu" button unselects.

I don't know if I should call this an issue or a request for a new feature, I pin the menu and when I start doing something the menu magically unpins itself, it may be the intended way for it to function, but it feels jittery.

**Comment by HakanSeven12** [comment]
Development stopped. Sorry.

**Comment by Bkk1234** [comment]
it is sad.however i want to fork this project. i have dream make flat icon s or material icons.may i fork it in open source lisense ?

**Comment by HakanSeven12** [comment]
This project has open source license https://github.com/HakanSeven12/Modern-UI/blob/master/LICENSE
