### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by dschick** [HakanSeven12/Modern-UI#3]
thanks for the great project.
Windows support seems not to work yet.
Is that correct? what are the plans?

**Comment by HakanSeven12** [comment]
I'm using and developing this mod on Windows 10.

**Comment by dschick** [comment]
ah, I have installed the mod, but there are no changes in the UI after a restart
I do use FreeCad 18.4.
Anything else I need to do after installing it with the Plugin manager?

**Comment by HakanSeven12** [comment]
It's not compatible with 0.18. You need to use 0.19.

**Comment by dschick** [comment]
okay, with 0.19 in runs out of the box.
So maybe one should add this requirement somewhere.

Anyhow, great work!

Closing

**Comment by HakanSeven12** [comment]
Thanks 🙂
