### ISSUE TITLE
"Cloning module..." hangs

### ISSUE THREAD

**Issue by 0xorial** [HakanSeven12/Modern-UI#5]
When I try to install this addon "Cloning module..." seems to never end. Is there a way to diagnose the problem?

**Comment by HakanSeven12** [comment]
I don't know the reason. It freezes but it continues to install at the background.

**Comment by 0xorial** [comment]
In the end it seemed not installed in v.18 but when I ran the v.19 alpha it was there (without additional installation). Is that normal?

**Comment by HakanSeven12** [comment]
V0.18 is not supported. You need to use v0.19.
