### ISSUE TITLE
Will not install/appear.

### ISSUE THREAD

**Issue by allaneploth** [HakanSeven12/Modern-UI#6]
Greetings. I have tried a dozen times to install the Modern UI with no success. The add-on manager indicates that it has been installed, but it doesn't appear in the toolbench dropdown list. I have uninstalled and reinstalled the latest version of FreeCAD with no success. Am I committing some kind of fundamental mistake? Should the Modern UI appear in the toolbench dropdown, or is there some other way to make it active. Many thanks in advance. -- Allan

**Comment by HakanSeven12** [comment]
What is your system informations?

**Comment by sar** [comment]
@HakanSeven12 

Seems to be replicable on linux, tried both AppImage and Flatpak variants of FreeCAD. The macro ``GetToolbars.FCMacro`` is registered but the rest of the extension does not enumerate just like an external workbench.

 ```
version 0.18 build 16146 (Git)

$ uname
5.8.13-200.fc32.x86_64 GNU/Linux
```

**Comment by HakanSeven12** [comment]
Its not compatible with 0.18. Use 0.19.
